---
title: 'Class 6: R Functions'
author: "Tyler Bogan"
date: "April 18, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 


## About
This is my **Class 6** R markdown document with my *codes* and notes for the day.
```{r}
plot(1:10, typ="l", col="blue")
```


##Reading files - Practice

There are 3 files to read

```{r}
read.table("test1.txt", header=TRUE, sep = ",")

```

```{r}
read.csv("test1.txt")
```

```{r}
read.table("test2.txt", header = TRUE, sep = "$")
```

```{r}
read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bimm143_S19/class-material/test1.txt")
```

## Functions

Our First Stilly function example:

```{r}
add <- function(x, y=1) {
  # The Body!!
  x + y
}
```


```{r}
add(10)
```


```{r}
add(10,10)
```


```{r}
add( c(1,2,3) )
```


```{r}
add( c(1,2,3), 4 )
```


```{r}
#add(1,2,3)
```


```{r}
rescale <- function(x) {
   rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale(1:10)
```


```{r}

rescale2 <- function(x, na.rm=TRUE) {
  rng <-range(x, na.rm=na.rm)
  (x-rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale( c(1,2,NA,3,10) )
```



```{r}
## rescale( c(1,10,"string") )
```




```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 
  rng <-range(x, na.rm=na.rm)
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")
 
 if(plot) {
   plot(answer, typ="b", lwd=4)
   }
 
 print("I can see it in ...")
 
 return(answer)
}
```

```{r}
rescale3( c(1,3,NA,10) )
```


